name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Instalar dependências Python
        run: |
          pip install --upgrade pip
          pip install cython buildozer

      - name: Instalar dependências sistema
        run: |
          sudo apt update
          sudo apt install -y zip unzip git

      - name: Instalar Android SDK
        run: |
          mkdir -p $HOME/android-sdk
          cd $HOME/android-sdk
          wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip
          unzip commandlinetools-linux-10406996_latest.zip
          mkdir -p cmdline-tools/latest
          mv cmdline-tools/* cmdline-tools/latest/ || true

      - name: Configurar variáveis Android
        run: |
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH

      - name: Aceitar licenças
        run: yes | sdkmanager --licenses

      - name: Instalar plataformas Android
        run: |
          sdkmanager \
                      "platform-tools" \
                      "platforms;android-33" \
                      "build-tools;33.0.2" \
                      "cmdline-tools;latest"

      - name: Gerar APK
        run: buildozer android debug
