name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependências Python
        run: |
          pip install --upgrade pip
          pip install cython buildozer

      - name: Instalar dependências do sistema
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jdk \
          autoconf libtool pkg-config zlib1g-dev \
          libncurses5-dev libncursesw5-dev libtinfo5 cmake \
          libffi-dev libssl-dev git

      - name: Build APK
        run: |
          buildozer android debug
